name: Pull Request

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/setup-workflow.yml

  unit-test:
    uses: ./.github/workflows/unit-test.yml
    needs: [setup]