name: Unit Test Workflow

on:
  workflow_call:
    inputs:
      module:
        description: 'Unit Test Module'
        type: string
        required: true

jobs:
  unit-test:
    name: unit test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules/
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            - cache-node-modules-

      - name: Run Unit Test
        run: npm run test:all